name: build

on:
  push:
    branches: ['*']
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      etherscan_api_key: ${{ secrets.ETHERSCAN_API_KEY }}
      goerli_rpc_key: ${{ secrets.GOERLI_RPC_KEY }}
      mainnet_rpc_key: ${{ secrets.MAINNET_RPC_KEY }}
      goerli_account_pk: ${{ secrets.GOERLI_ACCOUNT_PK }}
      mainnet_account_pk: ${{ secrets.MAINNET_ACCOUNT_PK }}
    steps:
      - name: Tests and setup
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
          submodules: recursive
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn install
      - run: yarn add git+https://${{ secrets.PAT }}:x-oauth-basic@github.com/Tisamenus/tornado-lottery-period.git#production
      - run: yarn lint
      - run: yarn test:all
        env:
          use_mock_proposal: false
          use_latest_block: false

      - name: Generate coverage
        run: yarn coverage
        env:
          use_mock_proposal: true
          use_latest_block: false
